Implement Module Toggling
terraria-catalyst/carbon-mod pull request #3
Opened 2024-05-01 15:26 UTC by BabyblueSheep

Implements toggling modules with a JSON file, found in `tModLoader\CarbonMod\enabled-modules.json`.

While the method I used was a simple list of enabled modules, perhaps it could be better to have individual boolean values for each module?
Additionally, it might be better to add a value to check if an assembly is a module, instead of relying on the name alone.

2024-05-01 16:55 UTC, OliHeamon requested changes
The from-config loading system is good, and the file saves to the ideal location.

In terms of changes, we need to keep track of which assemblies are loaded for user configuration purposes, and there needs to be a method to save the current list of loaded assemblies to a file. For the second one you can probably just make a helper method out of part of the loading code that creates and populates the config file.

2024-05-01 17:59 UTC, steviegt6 requested changes

2024-05-01 17:59 UTC, steviegt6 commented on src/Carbon/CarbonMod.cs
> +        public static readonly string ModuleConfigFile = Path.Join(Main.SavePath, "CarbonMod", "enabled-modules.json");
Prefer properties over resolving once; not a big deal, just preference.

2024-05-01 17:59 UTC, steviegt6 commented on src/Carbon/CarbonMod.cs
> +
gang

2024-05-01 17:59 UTC, steviegt6 commented on src/Carbon/CarbonMod.cs
> +                    }
Do we automatically handle enabling newly-introduced modules?

2024-05-03 08:45 UTC, BabyblueSheep commented
Writing the changes I've made for clarity:
- changed the `enabled-modules.json`; it now has a boolean for each module. This is so that newly added modules are automatically enabled
- added a custom assembly attribute for checking if an assembly is a module
- the mod now stores a dictionary of enabled modules and a list of loaded assemblies
- added a pre-build script that puts every referenced `.dll` in the `build.txt`

2024-05-03 20:46 UTC, OliHeamon approved these changes

2024-05-03 20:46 UTC, merged